In [333]:
import numpy as np
import pandas as pd

In [334]:
df = pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [335]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [336]:
df["Family_members_on_ship"] = df["SibSp"] + df["Parch"]

df = df.drop(["SibSp","Parch"],axis=1)

In [337]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_members_on_ship
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0

In [338]:
df["Family_on_board"] = df["Family_members_on_ship"] > 0
df

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,Family_members_on_ship,Family_on_board
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0,False
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3,True
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0,False

In [339]:
df_numerical = df[["Age","Fare","Family_members_on_ship"]]
df_categorical = df[["Survived","Pclass","Sex","Cabin","Embarked","Family_on_board"]]

In [340]:
def numerical_stats(num):
    stats = {}
    for i in num:
        stats[i] = { 
            "mean": num[i].mean(),
            "median": num[i].median(),
            "min": num[i].min(),
            "max": num[i].max(),
            "std": num[i].std(),
            "missing": num[i].isnull().sum()
        }
    return stats

In [341]:
def most_feq(num):
    max_count = num.value_counts().max()
    mask = num.value_counts() == max_count
    return num.value_counts()[mask].index.to_numpy()

In [342]:
def categorical_stats(num):
    stats = {}
    for i in num:
        stats[i] = {
             "most_frequent_value": most_feq(num[i]),
             "unique_counts": num[i].nunique()
        }
    return stats

In [343]:
def stats(numerical_df,categorical_df):
    stats = {
        "numerical_col": numerical_stats(numerical_df),
        "categorical_col": categorical_stats(categorical_df)
    }

    return stats

In [344]:
stats(df_numerical,df_categorical)

{'numerical_col': {'Age': {'mean': np.float64(29.69911764705882),
   'median': np.float64(28.0),
   'min': np.float64(0.42),
   'max': np.float64(80.0),
   'std': np.float64(14.526497332334042),
   'missing': np.int64(177)},
  'Fare': {'mean': np.float64(32.204207968574636),
   'median': np.float64(14.4542),
   'min': np.float64(0.0),
   'max': np.float64(512.3292),
   'std': np.float64(49.6934285971809),
   'missing': np.int64(0)},
  'Family_members_on_ship': {'mean': np.float64(0.9046015712682379),
   'median': np.float64(0.0),
   'min': np.int64(0),
   'max': np.int64(10),
   'std': np.float64(1.6134585413550873),
   'missing': np.int64(0)}},
 'categorical_col': {'Survived': {'most_frequent_value': array([0]),
   'unique_counts': 2},
  'Pclass': {'most_frequent_value': array([3]), 'unique_counts': 3},
  'Sex': {'most_frequent_value': array(['male'], dtype=object),
   'unique_counts': 2},
  'Cabin': {'most_frequent_value': array(['G6', 'C23 C25 C27', 'B96 B98'], dtype=object),
   'unique_counts': 147},
  'Embarked': {'most_frequent_value': array(['S'], dtype=object),
   'unique_counts': 3},
  'Family_on_board': {'most_frequent_value': array([False]),
   'unique_counts': 2}}}